name = "configuration"
version = "1.0.0"
description = ""
main = "index.js"
author = ""
license = "ISC"

[scripts]
test = "echo \"Error: no test specified\" && exit 1"

[dependencies]
@types/node = "^7.0.12"
ini = "^1.3.4"
msgpack = "^1.0.2"
qs = "^6.4.0"
toml-js = "0.0.8"
yamljs = "^0.2.9"

[devDependencies]
typescript = "^2.2.2"


